version: '3.8'

services:
  frontend:
    container_name: messagewall-frontend
    image: messagewall-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Frontend käyttää Nginxiä portissa 80
    environment:
      REACT_APP_BACKEND_URL: https://vaks.esedu.fi/api
      REACT_APP_SOCKET_URL: https://vaks.esedu.fi
      REACT_APP_SOCKET_PATH: /socket.io
      REACT_APP_BASENAME: /

  backend:
    container_name: messagewall-backend
    image: messagewall-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Backend kuuntelee porttia 5000
    environment:
      MONGODB_URI: mongodb://mongo:27017/messagewall
      JWT_SECRET: ${JWT_SECRET:-turvallinen_avain_tuotantoon}
      PORT: 5000
      FRONTEND_URL: https://vaks.esedu.fi
      SOCKET_IO_PATH: /socket.io
      BASE_URL: /api

      NODE_ENV: production # Tuotantoympäristö
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-TurvallisempiSalasana123}
      ADMIN_COLOR: "#FF0000"
    restart: unless-stopped

    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/usr/src/app/uploads  # Pysyvä tallennustila tiedostoille

  mongo:
    image: mongo:6.0
    container_name: messagewall-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
    name: messagewall-mongo-data

networks:
  default:
    name: messagewall-network