services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend
      - "5000:5000" # Backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/messagewall
      JWT_SECRET: your_jwt_secret
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
      SOCKET_IO_PATH: /socket.io
      BASE_URL: /api
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: